import { reactive } from "vue";

export const store = reactive({
  headerDirectories: [
    {
      name: "Business",
      //icon: faChartLine,
    },
    {
      name: "Design",
      //icon: faPalette,
    },
    {
      name: "Development",
      //icon: faGear,
    },
    {
      name: "Lifestyle",
      //icon: faFaceSmile,
    },
    {
      name: "Office Productivity",
      //icon: faPrint,
    },
  ],
  popularCourses: [
    {
      image: "/895786_7b4b_2-272x161.jpg",
      theme: "Development >",
      description: "The Complete iOS 10 & Swift3 Developer Course",
      rating: 4,
      price: "$199.99",
      discountedPrice: "$100",
    },
    {
      image: "/246154_d8b0_3-272x161.jpg",
      theme: "Development >",
      description: "Web Design for Beginners: Real World Coding in HTML & CSS",
      rating: 5,
      price: "$129.99",
      discountedPrice: "$65",
    },
    {
      image: "/752950_b773-272x161.jpg",
      theme: "Development >",
      description:
        "GitHub Ultimate: Master Git and GitHub - Beginner to Expert",
      rating: 4,
      price: "$99.99",
      discountedPrice: "$50",
    },
    {
      image: "/1253188_58f7_2-272x161.jpg",
      theme: "Development >",
      description:
        "The Complete iOS 11 & Swift Developer Course - Build 20 Apps",
      rating: 4,
      price: "$199.99",
      discountedPrice: "$100",
    },
    {
      image: "/919872_ed54_6-272x161.jpg",
      theme: "Development >",
      description: "Android Java Masterclass - Become an App Developer",
      rating: 4,
      price: "$99.99",
      discountedPrice: "$50",
    },
    {
      image: "/951684_9c1a_2-272x161.jpg",
      theme: "Development >",
      description: "Xamarin Forms: Build Native Cross-platform App with C#",
      rating: 4,
      price: "$109.99",
      discountedPrice: "$95",
    },
  ],
  recentCourses: [
    {
      image: "/895786_7b4b_2-272x161.jpg",
      theme: "Development >",
      description: "The Complete iOS 10 & Swift3 Developer Course",
      rating: 4,
      price: "$199.99",
      discountedPrice: "$100",
    },
    {
      image: "/1561458_7f3b-272x161.jpg",
      theme: "Design >",
      description: "Css - The Complete Guide 2020 (incl. Flexbox, Grid & Sass",
      rating: 5,
      price: "$199.99",
      discountedPrice: "$100",
    },
    {
      image: "/246154_d8b0_3-272x161.jpg",
      theme: "Development >",
      description: "Web Design for Beginner: Real World Coding in HTML & CSS",
      rating: 5,
      price: "$129.99",
      discountedPrice: "$65",
    },
    {
      image: "/1208228_d61c_4-272x161.jpg",
      theme: "Design >",
      description: "Digitally Painting Light and Color: Amateur to Master",
      rating: 4,
      price: "$139.99",
      discountedPrice: "$70",
    },
    {
      image: "/186792_41e4_4-272x161.jpg",
      theme: "Arts & Crafts >",
      description: "Become an Arabic Calligraphy Artist from Scratch",
      rating: 5,
      price: "$199.99",
      discountedPrice: "",
    },
    {
      image: "/1776542_30b1-272x161.jpg",
      theme: "Google >",
      description: "Google Searching Ninja!",
      rating: 4,
      price: "$89.99",
      discountedPrice: "$45",
    },
    {
      image: "/949316_2a64_11-272x161.jpg",
      theme: "Arts & Crafts >",
      description: "Foundations for Mastering Watercolor Painting",
      rating: 5,
      price: "$19.99",
      discountedPrice: "$10",
    },
    {
      image: "/366802_6fcc-272x161.jpg",
      theme: "Food & Beverage >",
      description: "Get Wine Smart",
      rating: 4,
      price: "$49.99",
      discountedPrice: "$25",
    },
    {
      image: "/381588_2e6d_4-272x161.jpg",
      theme: "Arts & Crafts >",
      description: "The Colored Pencil Drawing Course",
      rating: 4,
      price: "$34.99",
      discountedPrice: "$18",
    },
    {
      image: "/838056_611a_3-272x161.jpg",
      theme: "Arts & Crafts >",
      description:
        "Paint Realistic Watercolor and Botanicals - STUDIO - BASICS",
      rating: 4,
      price: "$69.99",
      discountedPrice: "$35",
    },
    {
      image: "/1414956_d944_15-272x161.jpg",
      theme: "Arts & Crafts >",
      description: "Mastering Brushstrokes - Part 1",
      rating: 5,
      price: "$19.99",
      discountedPrice: "$10",
    },
    {
      image: "/1109398_4c13-272x161.jpg",
      theme: "Arts & Crafts >",
      description: "Paint Realistic Watercolour and Botanicals - MAGNOLIAS",
      rating: 5,
      price: "$69.99",
      discountedPrice: "$35",
    },
  ],
  coursesDirectories: [
    "All Categories",
    "Business",
    "Design",
    "Development",
    "IT & Software",
    "Lifestyle",
    "Marketing",
    "Office Productivity",
  ],
});
